import React from "react";
import Head from "next/head";

export const CustomHead = (props) => {
  const { title } = props;
  return (
    <div>
      <Head>
        <title>{title} page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};
